title: Adam Becker
description: "writes code, rides bikes.<br />Oaklander in DC."

url: http://ada.mbecker.cc/wonderland
permalink: pretty

twitter: adamjacobbecker
github: adamjacobbecker
instagram_id: 1574083

server: true
auto: true