title: Adam Brown
description: Systems Engineer & Hacker

url: http://deftnerd.com
permalink: pretty

twitter: deftnerd
github: deftnerd
lastfm: lockle
lastfm_api_key: 5f3cb888207d6bc08c5f4509aabe51a0

server: true
auto: true
