title: Adam Becker
description: "writes code, rides bikes.<br />Oaklander in DC."

url: http://ada.mbecker.cc/wonderland
permalink: pretty

twitter: adamjacobbecker
github: adamjacobbecker

server: true
auto: true